# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetarApp', '0003_auto_20180622_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='metar',
            name='scode_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='metar',
            name=b'scode',
            field=models.CharField(max_length=15),
        ),
    ]
